
Problem: Implement a function to compute the gradients of the mean squared error
(MSE) loss with respect to the weights and bias of a linear regression model using PyTorch’s autograd. The model is defined as y = w · x + b, where w and b are learnable
parameters.


In [1]:
import torch

In [2]:
# input and true input
x = torch.tensor([1.0, 2.0, 3.0], requires_grad=False)   
y_true = torch.tensor([2.0, 4.0, 6.0], requires_grad=False) 

In [6]:
# make model 

 # random initial weight
w = torch.randn(1, requires_grad=True) 

# random initial bias
b = torch.randn(1, requires_grad=True)  

# make linear model
y_pred = w * x + b

In [7]:
y_pred

tensor([-1.3454, -2.3661, -3.3867], grad_fn=<AddBackward0>)

In [8]:
# calculat loss function
loss = ((y_pred - y_true) ** 2).mean()

In [9]:
loss

tensor(46.6094, grad_fn=<MeanBackward0>)

In [10]:
# calculate weight and bise
loss.backward()
# print the gredient
print(f"Gradient of w: {w.grad}")
print(f"Gradient of b: {b.grad}")

Gradient of w: tensor([-29.4917])
Gradient of b: tensor([-12.7321])


Problem: Approximate the Hessian matrix of a quadratic function f(w) = w
TAw +
b
Tw + c with respect to a weight vector w, where A is a symmetric matrix, b is a vector,
and c is a scalar. Use PyTorch to compute the Hessian via finite differences on the
gradients.

In [12]:
import torch

In [13]:
# take all input
A = torch.tensor([[2.0, 1.0], [1.0, 2.0]])
b = torch.tensor([1.0, 1.0])
c = 0.0
w = torch.tensor([1.0, 1.0], requires_grad=True)

In [18]:
# quadratic function
def f(w):
    # n f(w) = wTAw +bTw + c 
    return w @ A @ w + b @ w + c

# Hessian Approximation Function
# epsilon is a small positive number 
# using epsilon for 
def approximate_hessian(f, w, epsilon=1e-4):
    # first dimension 0
    n = w.shape[0]
    # make 2d matrix using zero
    hessian = torch.zeros((n, n))

    for i in range(n):
        for j in range(n):
            # clone weight and detach the gradient
            w_ij1 = w.clone().detach()
            w_ij2 = w.clone().detach()
            w_ij3 = w.clone().detach()
            w_ij4 = w.clone().detach()
            
            # first point evaluate 
            w_ij1[i] += epsilon
            w_ij1[j] += epsilon
            f1 = f(w_ij1)

            # second point evaluate 
            w_ij2[i] += epsilon
            w_ij2[j] -= epsilon
            f2 = f(w_ij2)

            # third point evaluate 
            w_ij3[i] -= epsilon
            w_ij3[j] += epsilon
            f3 = f(w_ij3)

            # fourth point evaluate 
            w_ij4[i] -= epsilon
            w_ij4[j] -= epsilon
            f4 = f(w_ij4)

            # calculate Hessian matrix element
            hessian[i, j] = (f1 - f2 - f3 + f4) / (4 * epsilon ** 2)

    return hessian

# calculate hessian
hessian_approx = approximate_hessian(f, w)
print("Approximated Hessian matrix:\n", hessian_approx)


Approximated Hessian matrix:
 tensor([[0., 0.],
        [0., 0.]])


#### Extracting Attention Maps from ViT
Problem: Given a pretrained Vision Transformer (ViT) model from torchvision, extract
the attention maps from the last transformer layer for a given input image. The attention
maps represent the attention weights across patches.


In [35]:
import torch
import torchvision.transforms as transforms
from torchvision.models import vit_b_16, ViT_B_16_Weights
from PIL import Image
import matplotlib.pyplot as plt

In [36]:
# use vit_b_16 pretrained model for extracting the attention map
# Evaluation Mode on 
weights = ViT_B_16_Weights.IMAGENET1K_V1
model = vit_b_16(weights=weights)
model.eval()

VisionTransformer(
  (conv_proj): Conv2d(3, 768, kernel_size=(16, 16), stride=(16, 16))
  (encoder): Encoder(
    (dropout): Dropout(p=0.0, inplace=False)
    (layers): Sequential(
      (encoder_layer_0): EncoderBlock(
        (ln_1): LayerNorm((768,), eps=1e-06, elementwise_affine=True)
        (self_attention): MultiheadAttention(
          (out_proj): NonDynamicallyQuantizableLinear(in_features=768, out_features=768, bias=True)
        )
        (dropout): Dropout(p=0.0, inplace=False)
        (ln_2): LayerNorm((768,), eps=1e-06, elementwise_affine=True)
        (mlp): MLPBlock(
          (0): Linear(in_features=768, out_features=3072, bias=True)
          (1): GELU(approximate='none')
          (2): Dropout(p=0.0, inplace=False)
          (3): Linear(in_features=3072, out_features=768, bias=True)
          (4): Dropout(p=0.0, inplace=False)
        )
      )
      (encoder_layer_1): EncoderBlock(
        (ln_1): LayerNorm((768,), eps=1e-06, elementwise_affine=True)
        (self_a

In [37]:
# vit model takes 224x224 resolution image
# random tensor (3x224x224) 
# 1 -> Batch size = 1 (single image)
# 3 → Number of channels = 3 (RGB image: Red, Green, Blue)
# 224 → Height = 224 pixels
# 224 → Width = 224 pixels
image_tensor = torch.rand(1, 3, 224, 224)  # (1, 3, 224, 224) = single batch


In [38]:
image_tensor

tensor([[[[0.8024, 0.2795, 0.1932,  ..., 0.2613, 0.1781, 0.1085],
          [0.8843, 0.2581, 0.9649,  ..., 0.7701, 0.5419, 0.5131],
          [0.9729, 0.4910, 0.4874,  ..., 0.8281, 0.4867, 0.5610],
          ...,
          [0.5736, 0.6731, 0.1394,  ..., 0.5691, 0.8458, 0.0503],
          [0.7601, 0.3977, 0.3076,  ..., 0.2838, 0.0606, 0.7408],
          [0.3916, 0.7141, 0.4038,  ..., 0.9294, 0.0501, 0.7921]],

         [[0.8157, 0.9733, 0.4187,  ..., 0.1206, 0.0885, 0.0943],
          [0.9279, 0.6150, 0.3141,  ..., 0.6188, 0.2974, 0.8068],
          [0.8529, 0.0814, 0.1165,  ..., 0.4217, 0.9741, 0.4775],
          ...,
          [0.2832, 0.7861, 0.2536,  ..., 0.9593, 0.9773, 0.2418],
          [0.7908, 0.2670, 0.6028,  ..., 0.1524, 0.8795, 0.4300],
          [0.2455, 0.3862, 0.2100,  ..., 0.4234, 0.4353, 0.9990]],

         [[0.9850, 0.0331, 0.6013,  ..., 0.4857, 0.1785, 0.4590],
          [0.7057, 0.3733, 0.0454,  ..., 0.7549, 0.3283, 0.2468],
          [0.7107, 0.9449, 0.6453,  ..., 0

In [39]:
# image processing


# ViT expects input normalized  When we input an image into a model it is very important to bring the pixel values of that image into a specific scale
normalize = transforms.Normalize(mean=(0.5, 0.5, 0.5), std=(0.5, 0.5, 0.5))
image_tensor = normalize(image_tensor[0]).unsqueeze(0)  # normalize and add batch dim

In [40]:
image_tensor

tensor([[[[ 0.6049, -0.4409, -0.6136,  ..., -0.4774, -0.6438, -0.7830],
          [ 0.7686, -0.4838,  0.9298,  ...,  0.5403,  0.0838,  0.0262],
          [ 0.9458, -0.0180, -0.0251,  ...,  0.6561, -0.0265,  0.1220],
          ...,
          [ 0.1471,  0.3462, -0.7211,  ...,  0.1382,  0.6916, -0.8995],
          [ 0.5202, -0.2046, -0.3847,  ..., -0.4324, -0.8788,  0.4817],
          [-0.2168,  0.4281, -0.1923,  ...,  0.8587, -0.8997,  0.5842]],

         [[ 0.6314,  0.9465, -0.1627,  ..., -0.7588, -0.8231, -0.8114],
          [ 0.8557,  0.2300, -0.3717,  ...,  0.2375, -0.4051,  0.6136],
          [ 0.7057, -0.8371, -0.7669,  ..., -0.1565,  0.9482, -0.0451],
          ...,
          [-0.4336,  0.5721, -0.4929,  ...,  0.9186,  0.9547, -0.5164],
          [ 0.5816, -0.4659,  0.2056,  ..., -0.6952,  0.7589, -0.1399],
          [-0.5089, -0.2275, -0.5800,  ..., -0.1532, -0.1295,  0.9979]],

         [[ 0.9700, -0.9337,  0.2025,  ..., -0.0286, -0.6430, -0.0821],
          [ 0.4114, -0.2534, -

In [41]:
image_tensor.shape

torch.Size([1, 3, 224, 224])

In [43]:
attention_maps = []

def get_attention_hook(module, input, output):
    # add the last attention weights
    attention_maps.append(output.detach())

last_layer = model.encoder.layers[-1]
hook = last_layer.register_forward_hook(get_attention_hook)

In [ ]:
# forword pass for attention map capture
with torch.no_grad():
    _ = model(image_tensor)

In [47]:

attn = attention_maps[0]  
print(attn.shape)
# 1 = batch size
# 12 = number of attention heads
# 197 = number of tokens (1 cls token + 196 patches)

torch.Size([1, 197, 768])


In [51]:
# without batch dimention frint the final attention
attn = attn.squeeze(0)

In [52]:
attn

tensor([[-0.5359,  0.1264, -0.2883,  ..., -0.2607, -0.2003, -0.5589],
        [ 0.1010,  0.0228, -0.1902,  ..., -0.1762, -0.7962,  0.3999],
        [-0.2186, -0.1464, -0.4058,  ...,  0.0102, -0.8314,  0.2934],
        ...,
        [-0.0853,  0.2059,  0.3173,  ..., -0.1650,  0.1142,  0.0279],
        [-0.0238,  0.0193,  0.0377,  ..., -0.3504, -0.4274, -0.9631],
        [-0.0923,  0.2822, -0.0173,  ..., -0.1071,  0.2371,  0.1881]])

In [53]:
print("Final attention map shape:", attn.shape)

Final attention map shape: torch.Size([197, 768])


#### Tracking NaN Loss in Neural Network Training

In [65]:
import torch
import torch.nn as nn
import torch.optim as optim

In [66]:
x = torch.randn(100, 10)  # 100 sample and 10 feature 
y = torch.randn(100, 1) # 100 sample 1 output

In [67]:
x[:10]

tensor([[ 0.1819, -0.1120, -2.1458, -0.4859, -1.3033, -0.4570,  0.2469, -1.2194,
         -0.2582,  0.0858],
        [-0.7510, -1.1118,  0.4471, -0.6111,  1.1213, -1.6391,  0.7507, -1.2618,
          0.1002,  1.1176],
        [ 0.1734, -1.5792,  0.7491, -2.0699,  1.4953,  3.1896, -0.3707, -0.9628,
         -0.0185, -1.6282],
        [-0.3732,  1.5758, -0.5482, -0.1535,  0.1364,  1.5858,  0.8812,  0.0963,
         -0.2514,  0.4571],
        [-0.4383, -1.4301,  1.5282,  0.0626, -0.5022,  0.6785, -0.4699, -1.1604,
         -1.2394, -0.0220],
        [-0.7503, -0.4902, -0.1781, -1.0816, -0.4587,  0.1975,  0.6374, -1.8795,
         -0.6517, -0.1663],
        [ 0.1712,  0.1701, -1.3009,  0.0247, -0.2914,  1.6297,  1.6237, -0.3812,
         -0.6858, -2.7643],
        [-0.4143,  0.0880, -0.3236,  1.0982,  0.7414,  1.2151,  0.0819, -0.4450,
          0.5569,  1.2754],
        [-0.2283,  0.3202,  1.1244,  0.5609, -1.9677, -1.1903, -0.4472,  1.3641,
          0.9237,  0.9335],
        [ 1.1041,  

In [68]:
y[:10]

tensor([[-1.1310],
        [ 0.4369],
        [ 0.0237],
        [-1.0993],
        [ 0.7240],
        [-1.0746],
        [ 1.8990],
        [-0.6824],
        [ 0.7463],
        [-0.0108]])

In [73]:
# make 2 layer nural network
class SimpleNN(nn.Module):
    def __init__(self):
        super(SimpleNN, self).__init__()
        self.layer1 = nn.Linear(10, 50)  # input size 10, hidden layer 50
        self.layer2 = nn.Linear(50, 1)   # hidden layer 50, output size 1

    def forward(self, x):
        x = torch.relu(self.layer1(x))  # use ReLU activation function
        x = self.layer2(x)
        return x

In [74]:
# setup model loss and optimization
model = SimpleNN()  # create model
criterion = nn.MSELoss()  # MSE loss function
optimizer = optim.SGD(model.parameters(), lr=10.0)

In [75]:
def train_model(x, y, model, criterion, optimizer, epochs=100):
    for epoch in range(epochs):
        optimizer.zero_grad()  # setup 0 gradient
        outputs = model(x)     # model input
        loss = criterion(outputs, y)  # calculate loss
        
        # check NaN  
        if torch.isnan(loss).any():
            print(f"NaN loss detected at epoch {epoch}")
            # if NaN is exists then return the epoch
            return epoch  

        loss.backward()  # backward propagation
        optimizer.step()  # wpdate optimization
    # if not NaN then return -1
    return -1 


In [76]:
# training the model
epoch_with_nan = train_model(x, y, model, criterion, optimizer)
print(f"Epoch with NaN loss: {epoch_with_nan}")

NaN loss detected at epoch 5
Epoch with NaN loss: 5
